return {
  { 'tpope/vim-capslock' },
  { 'tpope/vim-dispatch' },
  { 'tpope/vim-fugitive' },
  { 'tpope/vim-ragtag' },
  { 'tpope/vim-rails' },
  { 'tpope/vim-scriptease' },
  { 'tpope/vim-tbone' },
  { 'tpope/vim-sleuth' },
  { 'tpope/vim-git' },
  { 'tpope/vim-unimpaired' },
  { 'tpope/vim-projectionist' },
  { 'tpope/vim-abolish' },
  { 'tpope/vim-obsession' },
  { 'tpope/vim-apathy' },
  { 'tpope/vim-bundler' },
  { 'tpope/vim-dadbod', cmd = { 'DB', 'DBUI', 'DBUIToggle', 'DBUIFindBuffer' } },
  { 'tpope/vim-rbenv' },
  { 'junegunn/vim-easy-align', keys = { 'ga', { '<Plug>(EasyAlign)', mode = { 'n', 'x' } } } },
  { 'junegunn/gv.vim', cmd = 'GV' },
  { 'pangloss/vim-javascript' },
  { 'datanoise/vim-jsx-pretty' },
  { 'euclio/vim-markdown-composer' },
  { 'tpope/vim-haml' },
  { 'racer-rust/vim-racer' },
  { 'keith/swift.vim' },
  { 'vim-scripts/nginx.vim' },
  { 'kchmck/vim-coffee-script' },
  { 'tmux-plugins/vim-tmux' },
  { 'digitaltoad/vim-pug' },
  { 'ekalinin/Dockerfile.vim' },
  { 'hallison/vim-rdoc' },
  { 'groenewege/vim-less' },
  { 'jneen/ragel.vim' },
  { 'cespare/vim-toml' },
  { 'elixir-editors/vim-elixir' },
  { 'datanoise/vim-crystal' },
  { 'datanoise/vim-llvm' },
  { 'python-mode/python-mode', branch = 'develop' },
  { 'vim-ruby/vim-ruby' },
  { 'datanoise/vim-ruby-heredoc-syntax' },
  { 'plasticboy/vim-markdown' },
  { 'fatih/vim-go' },
  { 'godlygeek/tabular', cmd = 'Tabularize' },
  { 'datanoise/vim-indexed-search' },
  { 'vim-scripts/searchfold.vim' },
  { 'AndrewRadev/splitjoin.vim' },
  { 'datanoise/switch.vim' },
  { 'AndrewRadev/sideways.vim' },
  { 'wellle/targets.vim' },
  { 'datanoise/vim-cmdline-complete' },
  { 'rhysd/git-messenger.vim', cmd = 'GitMessenger' },
  { 'mhinz/vim-grepper', cmd = { 'Grepper', 'GrepperRg', 'GrepperAg', 'GrepperGrep', 'GrepperBuffer' } },
  { 'janko-m/vim-test', cmd = { 'TestNearest', 'TestFile', 'TestSuite', 'TestLast', 'TestVisit' } },
  { 'tweekmonster/exception.vim' },
  { 'mhinz/vim-randomtag' },
  { 'datanoise/bufexplorer' },
  { 'vimwiki/vimwiki', cmd = { 'VimwikiIndex', 'VimwikiTabIndex', 'VimwikiUISelect', 'VimwikiDiaryIndex' } },
  { 'lervag/vimtex' },
  { 'datanoise/vim-localvimrc' },
  { 'tweekmonster/startuptime.vim', cmd = 'StartupTime' },
  { 'sindrets/diffview.nvim', cmd = { 'DiffviewOpen', 'DiffviewFileHistory', 'DiffviewClose', 'DiffviewToggleFiles', 'DiffviewFocusFiles', 'DiffviewRefresh' } },
}
